apiVersion: v1
kind: Service
metadata:
  name: myspringbootapp
  labels:
    app: myspringbootapp
spec:
  selector:
    app: myspringbootapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9099
      
